# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parallel_dm_dtw <- function(lot, ii, jj, normalize, step_pattern, ws, threshold) {
    .Call(`_IncDTW_parallel_dm_dtw`, lot, ii, jj, normalize, step_pattern, ws, threshold)
}

parallel_dm_dtw_mv <- function(lot, ii, jj, normalize, step_pattern, dist_method, ws, threshold) {
    .Call(`_IncDTW_parallel_dm_dtw_mv`, lot, ii, jj, normalize, step_pattern, dist_method, ws, threshold)
}

parallel_dv_dtw <- function(Q, lot, normalize, step_pattern, ws, threshold) {
    .Call(`_IncDTW_parallel_dv_dtw`, Q, lot, normalize, step_pattern, ws, threshold)
}

parallel_dv_dtw_mv <- function(Q, lot, normalize, step_pattern, dist_method, ws, threshold) {
    .Call(`_IncDTW_parallel_dv_dtw_mv`, Q, lot, normalize, step_pattern, dist_method, ws, threshold)
}

cpp_dtw2vec_cm <- function(cm, step_pattern) {
    .Call(`_IncDTW_cpp_dtw2vec_cm`, cm, step_pattern)
}

cpp_dtw2vec_cm_inc <- function(gcm_lc, cm, step_pattern) {
    .Call(`_IncDTW_cpp_dtw2vec_cm_inc`, gcm_lc, cm, step_pattern)
}

cpp_dtw2vec_cm_ws_ea <- function(cm, step_pattern, ws, threshold) {
    .Call(`_IncDTW_cpp_dtw2vec_cm_ws_ea`, cm, step_pattern, ws, threshold)
}

cpp_dtw2vec_cm_ws_inc <- function(gcm_lc, cm, step_pattern, ws, ny) {
    .Call(`_IncDTW_cpp_dtw2vec_cm_ws_inc`, gcm_lc, cm, step_pattern, ws, ny)
}

cpp_dtw2vec <- function(x, y, step_pattern) {
    .Call(`_IncDTW_cpp_dtw2vec`, x, y, step_pattern)
}

cpp_dtw2vec_ws <- function(x, y, step_pattern, ws) {
    .Call(`_IncDTW_cpp_dtw2vec_ws`, x, y, step_pattern, ws)
}

cpp_dtw2vec_ea <- function(x, y, step_pattern, threshold) {
    .Call(`_IncDTW_cpp_dtw2vec_ea`, x, y, step_pattern, threshold)
}

cpp_dtw2vec_ws_ea <- function(x, y, step_pattern, ws, threshold) {
    .Call(`_IncDTW_cpp_dtw2vec_ws_ea`, x, y, step_pattern, ws, threshold)
}

cpp_dtw2vec_mv <- function(x, y, step_pattern, dist_method) {
    .Call(`_IncDTW_cpp_dtw2vec_mv`, x, y, step_pattern, dist_method)
}

cpp_dtw2vec_mv_ws_ea <- function(x, y, step_pattern, dist_method, ws, threshold) {
    .Call(`_IncDTW_cpp_dtw2vec_mv_ws_ea`, x, y, step_pattern, dist_method, ws, threshold)
}

cpp_dtw2vec_v32 <- function(x, y) {
    .Call(`_IncDTW_cpp_dtw2vec_v32`, x, y)
}

cpp_dtw2vec_inc <- function(x, newObs, gcm_lc, step_pattern) {
    .Call(`_IncDTW_cpp_dtw2vec_inc`, x, newObs, gcm_lc, step_pattern)
}

cpp_dtw2vec_inc_ws <- function(x, newObs, gcm_lc, ws, ny, step_pattern) {
    .Call(`_IncDTW_cpp_dtw2vec_inc_ws`, x, newObs, gcm_lc, ws, ny, step_pattern)
}

cpp_dtw2vec_inc_mv <- function(x, newObs, gcm_lc, dist_method, step_pattern) {
    .Call(`_IncDTW_cpp_dtw2vec_inc_mv`, x, newObs, gcm_lc, dist_method, step_pattern)
}

cpp_dtw2vec_inc_mv_ws <- function(x, newObs, gcm_lc, dist_method, ws, ny, step_pattern) {
    .Call(`_IncDTW_cpp_dtw2vec_inc_mv_ws`, x, newObs, gcm_lc, dist_method, ws, ny, step_pattern)
}

cpp_znorm <- function(x, mu_in = NULL, sd_in = NULL) {
    .Call(`_IncDTW_cpp_znorm`, x, mu_in, sd_in)
}

cpp_norm01 <- function(x, min_in = NULL, max_in = NULL) {
    .Call(`_IncDTW_cpp_norm01`, x, min_in, max_in)
}

cpp_cm <- function(x, y, dist_method, ws, nPrevObs) {
    .Call(`_IncDTW_cpp_cm`, x, y, dist_method, ws, nPrevObs)
}

cpp_diffm <- function(x, y, ws, nPrevObs) {
    .Call(`_IncDTW_cpp_diffm`, x, y, ws, nPrevObs)
}

GCM_Sakoe_cpp <- function(cM, ws, step_pattern) {
    .Call(`_IncDTW_GCM_Sakoe_cpp`, cM, ws, step_pattern)
}

IGCM_Sakoe_cpp <- function(gcmN, dmN, cmN, ws, step_pattern) {
    .Call(`_IncDTW_IGCM_Sakoe_cpp`, gcmN, dmN, cmN, ws, step_pattern)
}

GCM_cpp <- function(cM, step_pattern) {
    .Call(`_IncDTW_GCM_cpp`, cM, step_pattern)
}

IGCM_cpp <- function(gcmN, dmN, cmN, step_pattern) {
    .Call(`_IncDTW_IGCM_cpp`, gcmN, dmN, cmN, step_pattern)
}

BACKTRACK_cpp <- function(dm) {
    .Call(`_IncDTW_BACKTRACK_cpp`, dm)
}

BACKTRACK2IN_cpp <- function(dm, diffM) {
    .Call(`_IncDTW_BACKTRACK2IN_cpp`, dm, diffM)
}

BACKTRACK2II_cpp <- function(dm, diffM) {
    .Call(`_IncDTW_BACKTRACK2II_cpp`, dm, diffM)
}

normmat <- function(x) {
    .Call(`_IncDTW_normmat`, x)
}

